apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: a8af1f7eg-python 
  janus-idp.io/tekton: a8af1f7eg-python
  backstage.io/kubernetes-id: a8af1f7eg-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: a8af1f7eg-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml